name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust this to the correct Python version you are using

    - name: Install dependencies
      run: make install

    - name: Run the Flask server
      run: |
        make run &
        sleep 10  # Ensure the server has time to start before proceeding to any tests

    - name: Check server is running
      run: curl http://localhost:3000  # You can replace this with any test for checking if the server runs successfully
